title: Rene Verinaud Anguita Junior
favicon: /assets/img/cv.png
include_css:
  - /assets/css/custom.css
logo: assets/img/face.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
