title: Portfolio 

favicon: /assets/img/cv.png      # Caminho absoluto para o favicon
# include_css:                        # Inclui o CSS customizado em formato de lista
#   - /assets/css/custom.css
logo: /assets/img/face.png       # Caminho absoluto para o logo
show_downloads: false                # Mostra o botão de download do currículo
theme: jekyll-theme-cayman         # Tema definido como 'minimal'

# Descrição do currículo para SEO e compartilhamento
description: "Currículo de Rene Verinaud Anguita Junior – Cientista de Dados"

# remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"



# author:
#   name: Rene Verinaud Anguita Junior
#   email: renevajr@gmail.com
#   picture: /assets/img/face.png 


text_styles:
  justify_text: "text-align: justify;"
  center_text: "margin-left: auto; margin-right: auto;"
  max_width: "max-width: 800px;"