include_css:
  - /assets/css/custom.css


title: Rene Verinaud Anguita Junior

favicon: "/assets/img/cv.png"
logo: "/assets/img/face.png"

show_downloads: true
theme: jekyll-theme-minimal

social_links:
  github: "https://github.com/seu_usuario"
  linkedin: "https://linkedin.com/in/seu_usuario"
